apiVersion: v1
kind: PersistentVolume
metadata:
  name: rating-mongo-pv
  namespace: default
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/rating
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rating-mongo-pvc
  namespace: default
spec:
  storageClassName: standard
  volumeName: rating-mongo-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
