apiVersion: apps/v1
kind: Deployment
metadata:
  name: tags-postgresql-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tags-postgresql
  template:
    metadata:
      labels:
        app: tags-postgresql
    spec:
      containers:
        - name: tags-postgresql
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tags-postgresql
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: tags
          volumeMounts:
            - mountPath: /var/lib/posrgresql/data
              name: tags-postgresqldb
      volumes:
        - name: tags-postgresqldb
          persistentVolumeClaim:
            claimName: tags-postgresql-claim
---
apiVersion: v1
kind: Service
metadata:
  name: tags-postgresql-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: tags-postgresql
  ports:
    - name: tags-postgresql
      protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: tags-postgresql-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: tags-postgresql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
